-- Supabase schema for the Yomna Ehab portfolio.
-- Run this file before 02_seed.sql in the Supabase SQL Editor.

create table if not exists public.site_config (
  key text primary key,
  value text not null default ''
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null unique
);

create table if not exists public.software (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null unique
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null unique
);

create table if not exists public.career (
  id bigint generated by default as identity primary key,
  dates text not null,
  company text not null,
  role text not null,
  sort_order integer not null unique
);

create table if not exists public.projects (
  id integer primary key,
  title text not null,
  client text not null default '',
  main_category text not null,
  type text not null default '',
  description text not null default '',
  role text not null default '',
  software text[] not null default '{}',
  thumb_color text not null default '#123b34',
  video_url text not null default '',
  original_link text not null default '',
  views text not null default '',
  featured boolean not null default false,
  published boolean not null default true,
  sort_order integer not null unique
);

create table if not exists public.contact_project_types (
  id bigint generated by default as identity primary key,
  label text not null unique,
  sort_order integer not null unique
);

create table if not exists public.contact_budget_options (
  id bigint generated by default as identity primary key,
  label text not null unique,
  sort_order integer not null unique
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) <= 254 and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  project_type text not null check (char_length(project_type) between 1 and 100),
  budget text not null default '' check (char_length(budget) <= 100),
  message text not null check (char_length(message) between 1 and 4000),
  submitted_at timestamptz not null default now(),
  is_read boolean not null default false,
  is_archived boolean not null default false
);

create index if not exists projects_published_order_idx
  on public.projects (published, sort_order);
create index if not exists inquiries_submitted_at_idx
  on public.inquiries (submitted_at desc);

-- Public portfolio content can be read without authentication.
alter table public.site_config enable row level security;
alter table public.skills enable row level security;
alter table public.software enable row level security;
alter table public.brands enable row level security;
alter table public.career enable row level security;
alter table public.projects enable row level security;
alter table public.contact_project_types enable row level security;
alter table public.contact_budget_options enable row level security;
alter table public.inquiries enable row level security;

drop policy if exists "Public can read site config" on public.site_config;
create policy "Public can read site config" on public.site_config
  for select to anon, authenticated using (true);

drop policy if exists "Public can read skills" on public.skills;
create policy "Public can read skills" on public.skills
  for select to anon, authenticated using (true);

drop policy if exists "Public can read software" on public.software;
create policy "Public can read software" on public.software
  for select to anon, authenticated using (true);

drop policy if exists "Public can read brands" on public.brands;
create policy "Public can read brands" on public.brands
  for select to anon, authenticated using (true);

drop policy if exists "Public can read career" on public.career;
create policy "Public can read career" on public.career
  for select to anon, authenticated using (true);

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects" on public.projects
  for select to anon, authenticated using (published);

drop policy if exists "Public can read project type options" on public.contact_project_types;
create policy "Public can read project type options" on public.contact_project_types
  for select to anon, authenticated using (true);

drop policy if exists "Public can read budget options" on public.contact_budget_options;
create policy "Public can read budget options" on public.contact_budget_options
  for select to anon, authenticated using (true);

-- The public site may submit a message but cannot read, update, or delete inquiries.
drop policy if exists "Public can submit inquiries" on public.inquiries;
create policy "Public can submit inquiries" on public.inquiries
  for insert to anon, authenticated
  with check (
    char_length(name) between 1 and 100
    and char_length(email) <= 254
    and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
    and char_length(project_type) between 1 and 100
    and char_length(budget) <= 100
    and char_length(message) between 1 and 4000
  );

grant select on public.site_config, public.skills, public.software, public.brands,
  public.career, public.projects, public.contact_project_types,
  public.contact_budget_options to anon, authenticated;
grant insert (name, email, project_type, budget, message)
  on public.inquiries to anon, authenticated;

-- Public visitors may only insert inquiries. The static-site admin policies
-- and authenticated grants are added by 03_static_site_policies.sql.
